list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_f-11d",				title = "SW_F-11D" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_f-11d_spec",			title = "SW_F-11D Spec Ops" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_f-11d_shadow",			title = "SW_F-11D Shadow" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_f-11d_magma",			title = "SW_F-11D Magma" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_f-11d_phasma",			title = "SW_F-11D Phasma" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_f-11d_edit",			title = "SW_F-11D Improved" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_f-11d_spec_edit",		title = "SW_F-11D Spec Ops Improved" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_f-11d_shadow_edit",		title = "SW_F-11D Shadow Improved" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_f-11d_magma_edit",		title = "SW_F-11D Magma Improved" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_f-11d_phasma_edit",		title = "SW_F-11D Phasma Improved" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_f-11d_v2",			title = "SW_F-11D V2" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_f-11d_v2_edit",			title = "SW_F-11D V2 Improved" }  )